# Generated by Django 5.0.6 on 2024-05-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listing_user_bid_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="item",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
    ]
