# Generated by Django 5.0.6 on 2024-05-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_bid_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                related_name="watching", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
