# Generated by Django 5.0.6 on 2024-05-29 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_watchlist_alter_listing_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ManyToManyField(
                related_name="bidding", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publishing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
