# Generated by Django 5.0.6 on 2024-05-29 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_bid_user_alter_listing_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="user",
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ManyToManyField(
                related_name="comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
