# Generated by Django 5.0.6 on 2024-05-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_remove_bid_user_alter_comment_user_bid_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
    ]
