# Generated by Django 5.0.6 on 2024-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_remove_user_followers_user_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="online",
            field=models.BooleanField(default=True),
        ),
    ]
